#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
    path: /{_locale}
    controller: App\Controller\WishListController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
